remote_theme: mikearnaldi/just-the-docs

baseurl: "/eftar"
repository: "leonitousconforti/eftar"

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
"eftar on GitHub":
  - "https://github.com/leonitousconforti/eftar"
