name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24

      - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6

      - run: pnpm install
      - run: pnpm clean
      - run: pnpm codegen
      - run: pnpm docgen
      - run: git restore docs/_config.yml
      - run: git add src && git diff-index --cached HEAD --exit-code src
      - run: pnpm check
      - run: pnpm circular
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test
